In [1]:
import numpy as np
import matplotlib.pyplot as plt

### 2x2 대칭행렬로 고유값, 특이값분해를 해보겠습니다.

In [2]:
x=np.array([[1,2],[3,1]])    ;x #출력

array([[1, 2],
       [3, 1]])

In [3]:
# EVD : AV=λV
s,v=np.linalg.eig(x) ;np.linalg.eig(x)

(array([ 3.44948974, -1.44948974]),
 array([[ 0.63245553, -0.63245553],
        [ 0.77459667,  0.77459667]]))

In [4]:
# A = VΛV^-1
np.dot(np.dot(v,np.diag(s)),np.linalg.inv(v))

array([[1., 2.],
       [3., 1.]])

In [5]:
np.dot(v,v.T) #직교행렬검증

array([[8.00000000e-01, 1.66533454e-16],
       [1.66533454e-16, 1.20000000e+00]])

In [6]:
# SVD : A=U∑V^T
u,s,v = np.linalg.svd(x);np.linalg.svd(x)

(array([[-0.52573111, -0.85065081],
        [-0.85065081,  0.52573111]]),
 array([3.61803399, 1.38196601]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))

### 4x2 직사각행렬

In [7]:
A=np.array([[1,2],[3,1],[0,0],[0,0]]);A

array([[1, 2],
       [3, 1],
       [0, 0],
       [0, 0]])

In [8]:
# SVD : A=U∑V^T
u,s,v = np.linalg.svd(A)     ;np.linalg.svd(A)#출력 

(array([[-0.52573111, -0.85065081,  0.        ,  0.        ],
        [-0.85065081,  0.52573111,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([3.61803399, 1.38196601]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))

In [9]:
s=np.concatenate([np.diag(s),np.array([[0,0],[0,0]])],axis=0);s

array([[3.61803399, 0.        ],
       [0.        , 1.38196601],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [13]:
np.dot(np.dot(u,s),v)

array([[1., 2.],
       [3., 1.],
       [0., 0.],
       [0., 0.]])

In [59]:
# AA^T
AAT=np.dot(A,A.T)           ;np.dot(A,A.T)#출력 

array([[ 5,  5,  0,  0],
       [ 5, 10,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [253]:
# A^TA
ATA=np.dot(A.T,A)            ;np.dot(A.T,A)#출력 

array([[10,  5],
       [ 5,  5]])

In [343]:
# AA^Tu = λu 
s,u=np.linalg.eig(AAT);np.linalg.eig(AAT) 

(array([ 1.90983006, 13.09016994,  0.        ,  0.        ]),
 array([[-0.85065081, -0.52573111,  0.        ,  0.        ],
        [ 0.52573111, -0.85065081,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]))

In [313]:
# A^TAv = λv 
s,v=np.linalg.eig(ATA)       ;np.linalg.eig(ATA)#출력 

(array([13.09016994,  1.90983006]),
 array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]))

In [314]:
#s=np.concatenate([np.diag(s),np.array([[0,0],[0,0]])],axis=1)

In [321]:
s[np.nonzero(s)] 

array([ 1.90983006, 13.09016994])

In [322]:
# ∑ 매트릭스 모양으로 변형 
# s[np.nonzero(s)] nonzero index만 추출
s=np.concatenate([np.diag(s[np.nonzero(s)]),np.array([[0,0],[0,0]])],axis=0)
np.sqrt(s) #출력

array([[1.38196601, 0.        ],
       [0.        , 3.61803399],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [324]:
us=np.dot(u,np.sqrt(s))     ;us#출력 

array([[-1.1755705 , -1.90211303],
       [ 0.72654253, -3.07768354],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [347]:
# SVD : A=U∑V^T
np.dot(us,v.T)

array([[2., 1.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])

In [300]:
#s=np.concatenate([np.diag(s),np.array([[0],[0]])],axis=1)

In [235]:
np.linalg.svd(A)

(array([[-0.52573111, -0.85065081,  0.        ,  0.        ],
        [-0.85065081,  0.52573111,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([3.61803399, 1.38196601]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))

In [86]:
A=np.array([[3,6],[2,3],[0,0],[0,0]])

In [87]:
u,s,v=np.linalg.svd(A)
np.linalg.svd(A)

(array([[-0.8816746 , -0.47185793,  0.        ,  0.        ],
        [-0.47185793,  0.8816746 ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([7.60555128, 0.39444872]),
 array([[-0.47185793, -0.8816746 ],
        [ 0.8816746 , -0.47185793]]))